"use client";
/* eslint-disable @next/next/no-html-link-for-pages -- Auth and protected file downloads require full HTTP navigation. */
import {useEffect,useState} from "react";
import {ArrowLeft,ArrowRight,FileText,LoaderCircle,Plus} from "lucide-react";
import type {Work,Requirement,Evidence,Workspace as Org} from "../../lib/dove-types";
type Me={workspace:Org;user:{name:string;email:string};integrations:{ai:boolean;email:boolean;inbound:boolean}};
type Brief=Pick<Work,"id"|"title"|"customer"|"status">;
const fileUrl=(id:string)=>"/api/dove/file/"+id;
async function api<T=unknown>(path:string,method="GET",data?:unknown){
 const multipart=data instanceof FormData;
 const res=await fetch("/api/dove/"+path,{method,headers:method==="GET"?{}:{"X-Dove-Action":"1",...(!multipart?{"Content-Type":"application/json"}:{})},body:method==="GET"?undefined:multipart?data:JSON.stringify(data||{})});
 const result=await res.json();if(!res.ok)throw new Error((result as {error?:string}).error||"Please try again.");return result as T;
}
const fields=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();return new FormData(e.currentTarget)};
function EvidenceFields({work,initial}:{work:Work;initial?:Evidence}){
 const [id,setId]=useState(initial?.documentId||work.documents[0]?.id||"");const [page,setPage]=useState(initial?.page||1);const doc=work.documents.find(x=>x.id===id);
 return <fieldset><legend>Source evidence</legend><div className="d-form-grid"><label>Document<select name="documentId" value={id} onChange={e=>{setId(e.target.value);setPage(1)}} required>{work.documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Page<select name="page" value={page} onChange={e=>setPage(Number(e.target.value))}>{doc?.pages.map((_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label></div><details><summary>Read source page {page}</summary><pre>{doc?.pages[page-1]}</pre></details><label>Exact quote<textarea name="quote" defaultValue={initial?.quote||""} minLength={3} maxLength={1500} rows={3} required/></label><p className="d-muted">Copy a passage exactly from the source above. Dove checks the quote before saving.</p></fieldset>;
}
function evidence(f:FormData):Evidence[]{return [{documentId:String(f.get("documentId")),page:Number(f.get("page")),quote:String(f.get("quote"))}]}
export default function Workspace({displayName}:{displayName:string}){
 const [me,setMe]=useState<Me|null>(null),[ready,setReady]=useState(false),[list,setList]=useState<Brief[]>([]),[work,setWork]=useState<Work|null>(null),[view,setView]=useState("work"),[tab,setTab]=useState("Documents"),[create,setCreate]=useState(false),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[invitation,setInvitation]=useState(""),[inviteLink,setInviteLink]=useState(""),[editing,setEditing]=useState<string|null>(null);
 async function load(){const user=await api<Me>("me");setMe(user);setList(await api("work"))}
 async function run(action:()=>Promise<void>,message=""){if(busy)return;setBusy(true);setError("");setNotice("");try{await action();if(message)setNotice(message)}catch(e){setError(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 useEffect(()=>{const hash=new URLSearchParams(location.hash.slice(1));Promise.all([api<Me>("me"),api<Brief[]>("work")]).then(([user,items])=>{setMe(user);setList(items)}).catch(e=>{if(!String(e.message).includes("invitation"))setError(e.message)}).finally(()=>{setInvitation(hash.get("invite")||"");setReady(true)})},[]);
 async function change(suffix:string,method:string,data?:unknown){if(!work)return;const next=await api<Work>("work/"+work.id+"/"+suffix,method,data);setWork(next);setList(await api("work"))}
 const complete=!!work?.requirements.length&&work.requirements.every(r=>r.status==="satisfied"||r.status==="waived");
 const paused=!!me?.workspace.paused||!!work?.paused;
 return <div className="dove-app"><header className="d-header"><a className="d-logo" href="/">dove<span>.</span></a>{me&&<nav aria-label="Workspace navigation"><button className={view==="work"?"chosen":""} onClick={()=>{setView("work");setWork(null)}}>Work</button><button className={view==="settings"?"chosen":""} onClick={()=>setView("settings")}>Settings</button></nav>}<div className="d-account"><span>{me?.workspace.name||displayName}</span><a href="/signout-with-chatgpt?return_to=/">Sign out</a></div></header><main className="d-main">
 {busy&&<p className="d-busy" role="status"><LoaderCircle className="spinning" size={18}/> Saving your progress...</p>}{error&&<p className="d-error" role="alert">{error}</p>}{notice&&<p className="d-success" role="status">{notice}</p>}
 {!ready?<p>Opening your workspace...</p>:!me?<section className="d-card d-welcome"><p className="d-eyebrow">INVITATION ACCESS</p><h1>A place for your finished work.</h1><p>You are signed in as {displayName}. Enter your workspace invitation to begin.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api("accept","POST",{token:invitation.trim()});history.replaceState(null,"","/workspace");await load()},"Welcome to your workspace.")}}><label>Invitation code<input type="password" autoComplete="off" value={invitation} onChange={e=>setInvitation(e.target.value)} required/></label><button className="d-primary" disabled={busy}>Join workspace</button></form><p>No invitation yet? <a href="/#access">Request early access</a>.</p></section>:view==="settings"?<>
 <div className="d-title"><div><p className="d-eyebrow">YOUR WORKSPACE</p><h1>Make it yours.</h1><p>Business details appear on new invoices. Every member can review work and authorize a package.</p></div></div>
 <div className="d-columns"><section className="d-card"><h2>Business and automation</h2><form onSubmit={e=>{const f=fields(e);void run(async()=>{await api("settings","PUT",{name:f.get("name"),billing:f.get("billing"),paused:f.get("paused")==="on"});await load()},"Settings saved.")}}><label>Business name<input name="name" defaultValue={me.workspace.name} maxLength={200} required/></label><label>Billing details<textarea name="billing" defaultValue={me.workspace.billing} rows={5} maxLength={1500} placeholder="Business address, payment details and instructions" required/></label><label className="d-check"><input name="paused" type="checkbox" defaultChecked={!!me.workspace.paused}/>Pause AI analysis and outgoing email for this workspace</label><button className="d-primary" disabled={busy}>Save settings</button></form></section><section className="d-card"><h2>Connections</h2><p>OpenAI analysis: <strong>{me.integrations.ai?"Connected":"Not configured"}</strong></p><p>Email delivery: <strong>{me.integrations.email?"Configured; delivery requires your approval":"Not configured"}</strong></p><p className="d-muted">Automatic inbox processing and scheduled reminders are not active in this hosted version. You can upload received documents, record replies and download approved packages.</p><p className="d-muted">AI receives extracted document text when you choose Analyze. Files stay in private workspace storage until you delete the work item. Upload text-readable PDFs or TXT files up to 4 MB; 10 documents per work item and 64 MB per workspace.</p><a className="d-button" href="/api/dove/export">Export workspace records</a></section>
 <section className="d-card"><h2>Invite a teammate</h2><p>Invited teammates can access all documents and decisions in this workspace.</p><form onSubmit={e=>{const f=fields(e);void run(async()=>{const d=await api<{token:string}>("invite","POST",{email:f.get("email")});setInviteLink(location.origin+"/workspace#invite="+d.token)},"Invitation created. Share it privately with that teammate.")}}><label>Teammate email<input type="email" name="email" required/></label><button disabled={busy}>Create invitation</button></form>{inviteLink&&<label>Private invitation, expires in 72 hours<input readOnly value={inviteLink} onFocus={e=>e.target.select()}/></label>}</section></div></>:!work?<>
 <div className="d-title"><div><p className="d-eyebrow">THE LAST MILE</p><h1>Good work. Ready to wrap up.</h1><p>Gather the evidence, resolve what is missing, then approve the exact billing package.</p></div><button className="d-primary" onClick={()=>setCreate(!create)}><Plus size={18}/>New work item</button></div>
 {!!me.workspace.paused&&<p className="d-notice">Automation is paused. Add your billing details and resume it in Settings when you are ready to analyze documents.</p>}
 {create&&<section className="d-card"><h2>Start with the finished work</h2><form onSubmit={e=>{const f=fields(e);void run(async()=>{const w=await api<Work>("work","POST",{title:f.get("title"),customer:f.get("customer"),contactName:f.get("contactName"),email:f.get("email"),authorized:f.get("authorized")==="on",currency:f.get("currency"),description:f.get("description")});setWork(w);setTab("Documents");setCreate(false);setList(await api("work"))})}}><div className="d-form-grid"><label>Work title<input name="title" maxLength={200} required placeholder="Brand identity handoff"/></label><label>Customer business<input name="customer" maxLength={200} required/></label><label>Billing contact name<input name="contactName" maxLength={200} required/></label><label>Billing contact email<input name="email" type="email" maxLength={254} required/></label><label>Currency<select name="currency">{["USD","EUR","GBP","CAD","AUD"].map(c=><option key={c}>{c}</option>)}</select></label></div><label>What was completed?<textarea name="description" maxLength={2000} rows={3} required/></label><label className="d-check"><input name="authorized" type="checkbox" required/>I verified this contact is authorized to receive this customer&apos;s documents and billing package.</label><div className="d-actions"><button className="d-primary" disabled={busy}>Create work item</button><button type="button" onClick={()=>setCreate(false)}>Cancel</button></div></form></section>}
 <label className="d-search">Find work<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by work or customer"/></label><section className="d-card">{!list.length?<div className="d-empty"><FileText size={40}/><h2>A clean slate.</h2><p>Add your first finished job to get its paperwork moving.</p><button onClick={()=>setCreate(true)}>Add finished work</button></div>:<div className="d-list">{list.filter(w=>(w.title+" "+w.customer).toLowerCase().includes(search.toLowerCase())).map(w=><button key={w.id} disabled={busy} onClick={()=>void run(async()=>{setWork(await api("work/"+w.id));setTab("Documents");setEditing(null)})}><span>{w.title}<small>{w.customer}</small></span><span className="d-tag">{w.status}</span><ArrowRight size={18}/></button>)}</div>}</section></>:<>
 <button className="d-back" onClick={()=>{setWork(null);setError("");setNotice("")}}><ArrowLeft size={16}/>All work</button><div className="d-title"><div><p className="d-eyebrow">{work.customer}</p><h1>{work.title}</h1><p>{work.description}</p><span className="d-tag">{work.status}</span></div><div><p className="d-muted">Billing contact<br/>{work.contactName}<br/>{work.email}</p></div></div>
 <div className="d-tabs" role="tablist" aria-label="Work stages">{["Documents","Review","Resolve","Package"].map((t,i)=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>{setTab(t);setEditing(null)}}><span>0{i+1}</span>{t}</button>)}</div><div className="d-detail"><section className="d-card" role="tabpanel" aria-label={tab}>
 {tab==="Documents"&&<><h2>Bring the evidence together.</h2><p>Upload agreements, purchase orders, acceptance notes and existing invoices. Dove preserves the source pages beside each decision.</p><form onSubmit={e=>{const f=fields(e);void run(()=>change("document","POST",f),"Document saved. Review any earlier decisions against the new evidence.")}}><label>PDF or TXT, up to 4 MB<input name="file" type="file" accept=".pdf,.txt" required/></label><button disabled={busy||work.documents.length>=10}>Upload document</button></form><div className="d-documents">{work.documents.map(d=><details key={d.id}><summary><FileText size={17}/>{d.name}<span>{d.pages.length} page(s)</span></summary><a href={fileUrl(d.id)}>Download original</a>{d.pages.map((p,i)=><div key={i}><h3>Page {i+1}</h3><pre>{p}</pre></div>)}</details>)}</div><h3>Turn sources into a checklist.</h3><p className="d-muted">Analyze sends extracted text to OpenAI. Suggested requirements must be reviewed by you. A new analysis replaces the checklist and invalidates prior package approvals. {work.calls}/20 calls used.</p><button className="d-primary" disabled={busy||paused||!work.documents.length||!me.integrations.ai||work.calls>=20} onClick={()=>void run(async()=>{await change("analyze","POST");setTab("Review")},"Analysis saved. Review every proposed requirement.")}>Analyze documents</button>{paused&&<p className="d-muted">Resume automation in Settings and on this item to analyze.</p>}</>}
 {tab==="Review"&&<><div className="d-card-title"><h2>Evidence first. Your decision.</h2><button disabled={busy||!work.documents.length} onClick={()=>setEditing("new")}><Plus size={16}/>Add requirement</button></div><p>Only a person can mark a requirement satisfied or waived. Uploads and edits invalidate earlier package approvals.</p>{complete&&<p className="d-success">Every requirement is reviewed. You can assemble the billing package.</p>}{!work.requirements.length&&<p className="d-notice">Analyze your documents or add a source-linked requirement to begin.</p>}
 {[...work.requirements,...(editing==="new"?[{id:"new",title:"",category:"custom",status:"received",evidence:[],reason:""} as Requirement]:[])].map(r=><article className="d-requirement" key={r.id}><div className="d-card-title"><h3>{r.title||"New requirement"}</h3><span className="d-tag">{r.status}</span></div>{r.evidence.map((s,i)=><blockquote key={i}>{s.quote}<cite>{work.documents.find(d=>d.id===s.documentId)?.name}, page {s.page}</cite></blockquote>)}<p>{r.reason}</p>{r.reviewedBy&&<p className="d-muted">Reviewed by {r.reviewedBy}</p>}{editing===r.id?<form className="d-edit" onSubmit={e=>{const f=fields(e);void run(async()=>{await change("requirement","PUT",{...(r.id!=="new"?{id:r.id}:{}),requirement:{title:f.get("title"),category:f.get("category"),status:f.get("status"),reason:f.get("reason"),evidence:evidence(f)}});setEditing(null)},"Decision saved.")}}><label>Requirement<input name="title" defaultValue={r.title} maxLength={200} required/></label><div className="d-form-grid"><label>Category<select name="category" defaultValue={r.category}>{["purchase_order","acceptance","deliverable","amount","billing_recipient","custom"].map(v=><option key={v}>{v}</option>)}</select></label><label>Your decision<select name="status" defaultValue={r.status}>{["missing","received","conflict","satisfied","waived"].map(v=><option key={v}>{v}</option>)}</select></label></div><EvidenceFields work={work} initial={r.evidence[0]}/><label>Reason for this decision<textarea name="reason" defaultValue={r.reason} minLength={5} maxLength={1000} required/></label><div className="d-actions"><button className="d-primary" disabled={busy}>Save decision</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>:<button disabled={busy} onClick={()=>setEditing(r.id)}>Review requirement</button>}</article>)}</>}
 {tab==="Resolve"&&<><h2>Close the missing pieces.</h2>{!me.integrations.email&&<p className="d-notice">Email is not configured. Contact the customer through your existing email, then upload their reply or documents in Documents. Nothing is sent from this workspace yet.</p>}<form onSubmit={e=>{const f=fields(e);void run(()=>change("request","POST",{requirements:f.getAll("requirements"),body:f.get("body"),authorize:true}),"Request status saved. Check its provider status below.")}}><fieldset><legend>Missing requirements</legend>{work.requirements.filter(r=>r.status==="missing").map(r=><label className="d-check" key={r.id}><input type="checkbox" name="requirements" value={r.id}/>{r.title}</label>)}{!work.requirements.some(r=>r.status==="missing")&&<p>No requirements are marked missing.</p>}</fieldset><p>Recipient: <strong>{work.email}</strong></p><label>Request message<textarea name="body" minLength={10} maxLength={3000} rows={5} required/></label><label className="d-check"><input type="checkbox" required/>I authorize sending this exact request to the contact above.</label><button disabled={busy||paused||!me.integrations.email}>Authorize and send request</button></form>{work.requests.map(r=><details key={r.id}><summary>{new Date(r.created).toLocaleDateString()} · {r.status}</summary><pre>{r.body}</pre><p className="d-muted">Provider acceptance is not proof of delivery. Do not resend an uncertain request until its provider record is checked.</p><form onSubmit={e=>{const f=fields(e);void run(()=>change("reply","POST",{requestId:r.id,sender:f.get("sender"),text:f.get("text"),verified:true}),"Reply recorded. Review its evidence before changing requirements.")}}><h3>Record a reply you received</h3><label>Verified sender<input type="email" name="sender" defaultValue={r.recipient} required/></label><label>Reply text<textarea name="text" minLength={10} maxLength={20000} required/></label><label className="d-check"><input type="checkbox" required/>I checked the original message and verified the sender and text.</label><button disabled={busy}>Record verified reply</button></form></details>)}</>}
 {tab==="Package"&&<><h2>A good job. All wrapped up.</h2><p>Assemble an immutable package, check the actual PDF and attachments, then approve that version. Delivery is a separate action.</p>{!complete&&<p className="d-notice">Review and resolve every requirement before assembling a package.</p>}
 {work.packages.map(p=><article key={p.id} className="d-packet"><span className="d-tag">{p.approved?"Approved":p.revision===work.revision?"Needs approval":"Outdated - create a new version"}</span><h3>{p.number}</h3><p className="d-amount">{p.currency} {p.total}</p><p>{p.summary}</p><p>Recipient: {p.recipient}</p><div className="d-actions"><a className="d-button" href={fileUrl(p.pdfId||p.id)+"?preview=1"} target="_blank" rel="noreferrer">Review invoice PDF</a><a className="d-button" href={fileUrl(p.id)}>Download package ZIP</a></div><details><summary>Exact version fingerprint</summary><code>{p.digest}</code></details>{!p.approved&&p.revision===work.revision&&<form onSubmit={e=>{e.preventDefault();void run(()=>change("approve","POST",{id:p.id,digest:p.digest,authorize:true}),"This exact package is approved.")}}><label className="d-check"><input type="checkbox" required/>I reviewed the downloaded invoice, recipient, amounts and supporting files and approve this exact version.</label><button disabled={busy||!complete}>Approve package</button></form>}{p.approved&&<p className="d-muted">Approved by {p.approvedBy}. Delivery: {p.delivery}</p>}{p.approved&&p.delivery==="not_sent"&&<form onSubmit={e=>{e.preventDefault();void run(()=>change("deliver","POST",{id:p.id,digest:p.digest,authorize:true}),"Delivery status saved.")}}><label className="d-check"><input type="checkbox" required/>I authorize emailing this approved package to {p.recipient}.</label><button className="d-primary" disabled={busy||paused||!me.integrations.email}>Authorize and send package</button>{!me.integrations.email&&<p className="d-muted">Email is not configured. Download and deliver the approved ZIP through your existing process.</p>}</form>}</article>)}
 <details open={!work.packages.length}><summary>Assemble {work.packages.length?"a new version":"your first package"}</summary><form onSubmit={e=>{const f=fields(e);void run(()=>change("package","POST",{total:f.get("total"),issue:f.get("issue"),due:f.get("due"),summary:f.get("summary"),evidence:evidence(f),documents:f.getAll("documents"),...(f.get("existingInvoice")?{existingInvoice:f.get("existingInvoice")} :{}),confirmed:true}),"Package assembled. Review the PDF and ZIP before approval.")}}><label>Invoice<select name="existingInvoice"><option value="">Generate a simple invoice from the confirmed total</option>{work.documents.filter(d=>d.mime==="application/pdf").map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="d-form-grid"><label>Confirmed total ({work.currency})<input type="text" inputMode="decimal" name="total" pattern="[0-9]{1,9}(\.[0-9]{1,2})?" placeholder="2400.00" required/></label><label>Invoice date<input type="date" name="issue" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Due date<input type="date" name="due" required/></label></div><EvidenceFields work={work}/><label>Completion summary<textarea name="summary" minLength={5} maxLength={2000} rows={4} required defaultValue={work.description}/></label><fieldset><legend>Supporting documents</legend>{work.documents.map(d=><label className="d-check" key={d.id}><input type="checkbox" name="documents" value={d.id} defaultChecked/>{d.name}</label>)}</fieldset><label className="d-check"><input type="checkbox" required/>I verified the total, tax treatment, dates and billing recipient against the source. For an existing invoice, I verified its contents match these details.</label><button className="d-primary" disabled={busy||!complete||!work.documents.length}>Assemble package for review</button></form></details></>}
 </section><aside><section className="d-card"><h2>Activity</h2><p className="d-muted">Saved decisions stay with this work.</p><ul className="d-activity">{work.activity.map((a,i)=><li key={i}><time>{new Date(a.at).toLocaleString()}</time><p>{a.text}</p><small>{a.by}</small></li>)}</ul></section><section className="d-card"><h3>Work controls</h3><p className="d-muted">Automation: {work.paused?"paused for this work":me.workspace.paused?"paused in Settings":"enabled"}</p><button disabled={busy} onClick={()=>void run(()=>change("pause","POST",{paused:!work.paused}))}>{work.paused?"Resume this work":"Pause this work"}</button><details><summary>Delete this work</summary><p>This removes documents, packages and saved decisions. Export what you need first.</p><button className="d-danger" disabled={busy} onClick={()=>{if(confirm("Permanently delete this work item and its documents?"))void run(async()=>{await api("work/"+work.id,"DELETE");setWork(null);setList(await api("work"))},"Work deleted.")}}>Delete work item</button></details></section></aside></div>
 </>}
 </main></div>;
}

