"use client";
import {useEffect,useState,useRef} from "react";
import {ArrowLeft,ArrowRight,FileText,LoaderCircle,Plus} from "lucide-react";
import type {Work,Requirement,Evidence,Workspace as Org} from "../../lib/dove-types";
import AnalysisOptions from "../../components/analysis-options";
import {analyzeDocumentsBrowser} from "../../lib/browser-analysis.mjs";
import {analyzeDocumentsHosted,HOSTED_CHARACTER_LIMIT} from "../../lib/hosted-analysis.mjs";
import {stopDownload} from "../../lib/browser-model.mjs";
type Me={workspace:Org;user:{name:string;email:string};integrations:{ai:boolean;email:boolean;inbound:boolean}};
type Brief=Pick<Work,"id"|"title"|"customer"|"status">;
import {localApi as api} from "../../lib/dove-local";
import {downloadFile} from "../../lib/dove-storage";
import {exportBackup,importBackup} from "../../lib/dove-backup";
const fields=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();return new FormData(e.currentTarget)};
function EvidenceFields({work,initial}:{work:Work;initial?:Evidence}){
 const [id,setId]=useState(initial?.documentId||work.documents[0]?.id||"");const [page,setPage]=useState(initial?.page||1);const doc=work.documents.find(x=>x.id===id);
 return <fieldset><legend>Source evidence</legend><div className="d-form-grid"><label>Document<select name="documentId" value={id} onChange={e=>{setId(e.target.value);setPage(1)}} required>{work.documents.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Page<select name="page" value={page} onChange={e=>setPage(Number(e.target.value))}>{doc?.pages.map((_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></label></div><details><summary>Read source page {page}</summary><pre>{doc?.pages[page-1]}</pre></details><label>Exact quote<textarea name="quote" defaultValue={initial?.quote||""} minLength={3} maxLength={1500} rows={3} required/></label><p className="d-muted">Copy a passage exactly from the source above. Dove checks the quote before saving.</p></fieldset>;
}
function evidence(f:FormData):Evidence[]{return [{documentId:String(f.get("documentId")),page:Number(f.get("page")),quote:String(f.get("quote"))}]}
function reviewEvidence(f:FormData,original:Evidence[]):Evidence[]{const first=evidence(f)[0];return [first,...original.slice(1).filter(item=>item.documentId!==first.documentId||item.page!==first.page||item.quote!==first.quote)]}
export default function Workspace(){
 const [me,setMe]=useState<Me|null>(null),[ready,setReady]=useState(false),[list,setList]=useState<Brief[]>([]),[work,setWork]=useState<Work|null>(null),[view,setView]=useState("work"),[tab,setTab]=useState("Documents"),[create,setCreate]=useState(false),[search,setSearch]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[editing,setEditing]=useState<string|null>(null);
 const analysisController=useRef<AbortController|null>(null);const [analysisProgress,setAnalysisProgress]=useState("");const [analyzing,setAnalyzing]=useState(false);
 const [analysisMode,setAnalysisMode]=useState<'browser'|'hosted'>('browser'),[apiKey,setApiKey]=useState(''),[hostedModel,setHostedModel]=useState('gpt-5.4');
 useEffect(()=>()=>analysisController.current?.abort(),[]);
 async function analyzeHere(){if(!work||busy)return;const snapshot=work,control=new AbortController();analysisController.current=control;setAnalyzing(true);setBusy(true);setError("");setNotice("");try{const requirements=await (analysisMode==='hosted'?analyzeDocumentsHosted(snapshot,{apiKey,model:hostedModel,signal:control.signal,onProgress:setAnalysisProgress}):analyzeDocumentsBrowser(snapshot,{signal:control.signal,onProgress:setAnalysisProgress}));control.signal.throwIfAborted();await change("analyze","POST",{revision:snapshot.revision,requirements});setTab("Review");setNotice("Analysis saved. Review every proposed requirement and check for omissions.")}catch(e){if(e instanceof Error&&e.name==="AbortError")setNotice("Analysis stopped. Your prior checklist is unchanged.");else setError(e instanceof Error?e.message:"Analysis could not finish.")}finally{analysisController.current=null;setAnalyzing(false);setAnalysisProgress("");setBusy(false)}}
 async function load(){const user=await api<Me>("me");setMe(user);setList(await api("work"))}
 async function run(action:()=>Promise<void>,message=""){if(busy)return;setBusy(true);setError("");setNotice("");try{await action();if(message)setNotice(message)}catch(e){setError(e instanceof Error?e.message:"Please try again.")}finally{setBusy(false)}}
 useEffect(()=>{let active=true;Promise.all([api<Me>("me"),api<Brief[]>("work")]).then(([user,items])=>{if(active){setMe(user);setList(items)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setReady(true)});return()=>{active=false}},[]);
 async function change(suffix:string,method:string,data?:unknown){if(!work)return;const next=await api<Work>("work/"+work.id+"/"+suffix,method,data);setWork(next);setList(await api("work"))}
 const complete=!!work?.requirements.length&&work.requirements.every(r=>r.status==="satisfied"||r.status==="waived");
 const paused=!!me?.workspace.paused||!!work?.paused;
 const sourceCharacters=work?.documents.reduce((total,document)=>total+document.pages.reduce((length,page)=>length+page.length,0),0)||0;
 return <div className="dove-app"><header className="d-header"><a className="d-logo" href="/">dove<span>.</span></a>{me&&<nav aria-label="Workspace navigation"><button className={view==="work"?"chosen":""} disabled={busy} onClick={()=>{setView("work");setWork(null)}}>Work</button><button className={view==="settings"?"chosen":""} disabled={busy} onClick={()=>setView("settings")}>Settings</button></nav>}<div className="d-account"><span>{me?.workspace.name||"My workspace"}</span><span>Saved in this browser</span></div></header><main className="d-main">
 {busy&&<p className="d-busy" role="status"><LoaderCircle className="spinning" size={18}/> {analyzing?(analysisMode==='hosted'?"Analyzing documents with OpenAI…":"Analyzing documents on your device…"):"Saving your progress…"}</p>}{error&&<p className="d-error" role="alert">{error}</p>}{notice&&<p className="d-success" role="status">{notice}</p>}
 {!ready?<p>Opening your workspace...</p>:!me?<section className="d-card"><h1>Browser storage is unavailable.</h1><p>Enable site storage, then reload Dove. No account is required.</p><button onClick={()=>location.reload()}>Try again</button></section>:view==="settings"?<>
 <div className="d-title"><div><p className="d-eyebrow">YOUR WORKSPACE</p><h1>Make it yours.</h1><p>Business details appear on new invoices. Documents and decisions stay in this browser profile.</p></div></div>
 <div className="d-columns"><section className="d-card"><h2>Business and automation</h2><form onSubmit={e=>{const f=fields(e);void run(async()=>{await api("settings","PUT",{name:f.get("name"),billing:f.get("billing"),paused:f.get("paused")==="on"});await load()},"Settings saved.")}}><label>Business name<input name="name" defaultValue={me.workspace.name} maxLength={200} required/></label><label>Billing details<textarea name="billing" defaultValue={me.workspace.billing} rows={5} maxLength={1500} placeholder="Business address, payment details and instructions" required/></label><label className="d-check"><input name="paused" type="checkbox" defaultChecked={!!me.workspace.paused}/>Pause document analysis for this workspace</label><button className="d-primary" disabled={busy}>Save settings</button></form></section><section className="d-card"><h2>Your data, on this device</h2><p>No account or API key is needed for device analysis or manual review. Optional hosted analysis uses your own OpenAI API key and sends extracted document text to OpenAI.</p><p>Files and decisions are saved in this browser profile. They do not sync to other browsers, devices or teammates. Anyone using this profile can open them.</p><p>Clearing site data, private browsing or browser storage cleanup can remove saved work. Export regular backups. Backups contain your documents and are not encrypted.</p><p>Upload text-readable PDFs or TXT files up to 4 MB; 10 documents per work item and 64 MB of stored files per workspace.</p><button disabled={busy} onClick={()=>void run(exportBackup,"Backup downloaded. Keep it somewhere private.")}>Export complete backup</button><button disabled={busy} onClick={()=>void run(async()=>{const kept=await navigator.storage?.persist?.();setNotice(kept?"Persistent storage granted. Keep backups too.":"This browser did not grant persistent storage. Keep regular backups.")})}>Request persistent storage</button></section>
 <section className="d-card"><h2>Restore a backup</h2><p>Restore a Dove browser backup ZIP, including documents and packages. This replaces this browser’s current workspace. Export your current work first. Restored packages require approval again.</p><form onSubmit={e=>{const f=fields(e).get("backup");if(f instanceof File&&confirm("Replace this browser's workspace with this backup? Export current work first."))void run(async()=>{await importBackup(f);setWork(null);await load()},"Backup restored. Review restored packages before approving or delivering them.")}}><label>Complete Dove backup ZIP<input name="backup" type="file" accept=".zip" required/></label><button disabled={busy}>Restore backup</button></form></section></div></>:!work?<>
 <p className="d-notice">Your workspace is saved in this browser only. Use Settings to export a complete backup before clearing browser data or changing devices.</p><div className="d-title"><div><p className="d-eyebrow">THE LAST MILE</p><h1>Good work. Ready to wrap up.</h1><p>Gather the evidence, resolve what is missing, then approve the exact billing package.</p></div><button className="d-primary" onClick={()=>setCreate(!create)}><Plus size={18}/>New work item</button></div>
 {!!me.workspace.paused&&<p className="d-notice">Automation is paused. Add your billing details and resume it in Settings when you are ready to analyze documents.</p>}
 {create&&<section className="d-card"><h2>Start with the finished work</h2><form onSubmit={e=>{const f=fields(e);void run(async()=>{const w=await api<Work>("work","POST",{title:f.get("title"),customer:f.get("customer"),contactName:f.get("contactName"),email:f.get("email"),authorized:f.get("authorized")==="on",currency:f.get("currency"),description:f.get("description")});setWork(w);setTab("Documents");setCreate(false);setList(await api("work"))})}}><div className="d-form-grid"><label>Work title<input name="title" maxLength={200} required placeholder="Brand identity handoff"/></label><label>Customer business<input name="customer" maxLength={200} required/></label><label>Billing contact name<input name="contactName" maxLength={200} required/></label><label>Billing contact email<input name="email" type="email" maxLength={254} required/></label><label>Currency<select name="currency">{["USD","EUR","GBP","CAD","AUD"].map(c=><option key={c}>{c}</option>)}</select></label></div><label>What was completed?<textarea name="description" maxLength={2000} rows={3} required/></label><label className="d-check"><input name="authorized" type="checkbox" required/>I verified this contact is authorized to receive this customer&apos;s documents and billing package.</label><div className="d-actions"><button className="d-primary" disabled={busy}>Create work item</button><button type="button" onClick={()=>setCreate(false)}>Cancel</button></div></form></section>}
 <label className="d-search">Find work<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by work or customer"/></label><section className="d-card">{!list.length?<div className="d-empty"><FileText size={40}/><h2>A clean slate.</h2><p>Add your first finished job to get its paperwork moving.</p><button onClick={()=>setCreate(true)}>Add finished work</button></div>:<div className="d-list">{list.filter(w=>(w.title+" "+w.customer).toLowerCase().includes(search.toLowerCase())).map(w=><button key={w.id} disabled={busy} onClick={()=>void run(async()=>{setWork(await api("work/"+w.id));setTab("Documents");setEditing(null)})}><span>{w.title}<small>{w.customer}</small></span><span className="d-tag">{w.status}</span><ArrowRight size={18}/></button>)}</div>}</section></>:<>
 <button className="d-back" disabled={busy} onClick={()=>{setWork(null);setError("");setNotice("")}}><ArrowLeft size={16}/>All work</button><div className="d-title"><div><p className="d-eyebrow">{work.customer}</p><h1>{work.title}</h1><p>{work.description}</p><span className="d-tag">{work.status}</span></div><div><p className="d-muted">Billing contact<br/>{work.contactName}<br/>{work.email}</p></div></div>
 <div className="d-tabs" role="tablist" aria-label="Work stages">{["Documents","Review","Resolve","Package"].map((t,i)=><button key={t} role="tab" aria-selected={tab===t} disabled={busy} onClick={()=>{setTab(t);setEditing(null)}}><span>0{i+1}</span>{t}</button>)}</div><div className="d-detail"><section className="d-card" role="tabpanel" aria-label={tab}>
 {tab==="Documents"&&<><h2>Bring the evidence together.</h2><p>Add agreements, purchase orders, acceptance notes and existing invoices from your device. Dove preserves the source pages beside each decision.</p><form onSubmit={e=>{const f=fields(e);void run(()=>change("document","POST",f),"Document saved. Review any earlier decisions against the new evidence.")}}><label>PDF or TXT, up to 4 MB<input name="file" type="file" accept=".pdf,.txt" required/></label><button disabled={busy||work.documents.length>=10}>Add document</button></form><div className="d-documents">{work.documents.map(d=><details key={d.id}><summary><FileText size={17}/>{d.name}<span>{d.pages.length} page(s)</span></summary><button disabled={busy} onClick={()=>void run(()=>downloadFile(d.id))}>Download original</button>{d.pages.map((p,i)=><div key={i}><h3>Page {i+1}</h3><pre>{p}</pre></div>)}</details>)}</div><h3>Turn sources into a checklist.</h3><p className="d-muted">Choose device analysis or hosted analysis with your own API key. Suggested requirements must be reviewed by you. Saving a new analysis replaces the checklist and invalidates prior package approvals. Files and saved decisions remain in this browser’s local storage.</p><AnalysisOptions sourceCharacters={sourceCharacters} mode={analysisMode} apiKey={apiKey} model={hostedModel} busy={busy} onMode={mode=>{stopDownload();setAnalysisMode(mode);if(mode==='browser')setApiKey('');setError('');setNotice(mode==='browser'?'Device mode selected. API key cleared.':'Hosted analysis selected. Usage is billed to your OpenAI API account.')}} onKey={key=>{setApiKey(key);setError('');if(!key)setNotice('API key cleared.')}} onModel={model=>{setHostedModel(model);setError('')}}/><button className="d-primary" disabled={busy||paused||!work.documents.length||(analysisMode==='hosted'&&sourceCharacters>HOSTED_CHARACTER_LIMIT)} onClick={()=>void analyzeHere()}>{analysisMode==='hosted'?'Analyze with OpenAI':'Analyze documents'}</button>{analysisProgress&&<div role="status"><p>{analysisProgress}</p>{analysisMode==='hosted'&&<p className="d-muted">Stop requests cancellation and prevents saving partial proposals. Usage already incurred may still be billed.</p>}<button onClick={()=>analysisController.current?.abort()}>Stop analysis</button></div>}{paused&&<p className="d-muted">Resume automation in Settings and on this item to analyze.</p>}</>}
 {tab==="Review"&&<><div className="d-card-title"><h2>Evidence first. Your decision.</h2><button disabled={busy||!work.documents.length} onClick={()=>setEditing("new")}><Plus size={16}/>Add requirement</button></div><p>Only a person can mark a requirement satisfied or waived. Compare invoice dates with any agreed payment terms, and add missing checklist items from the source documents. Uploads and edits invalidate earlier package approvals.</p>{complete&&<p className="d-success">Every recorded checklist item is reviewed. Check the source documents for omissions before assembling the billing package.</p>}{!work.requirements.length&&<p className="d-notice">Analyze your documents or add a source-linked requirement to begin.</p>}
 {[...work.requirements,...(editing==="new"?[{id:"new",title:"",category:"custom",status:"received",evidence:[],reason:""} as Requirement]:[])].map(r=><article className="d-requirement" key={r.id}><div className="d-card-title"><h3>{r.title||"New requirement"}</h3><span className="d-tag">{r.status}</span></div>{r.evidence.map((s,i)=><blockquote key={i}>{s.quote}<cite>{work.documents.find(d=>d.id===s.documentId)?.name}, page {s.page}</cite></blockquote>)}<p>{r.reason}</p>{r.reviewedBy&&<p className="d-muted">Reviewed by {r.reviewedBy}</p>}{editing===r.id?<form className="d-edit" onSubmit={e=>{const f=fields(e);void run(async()=>{await change("requirement","PUT",{...(r.id!=="new"?{id:r.id}:{}),requirement:{title:f.get("title"),category:f.get("category"),status:f.get("status"),reason:f.get("reason"),evidence:reviewEvidence(f,r.evidence)}});setEditing(null)},"Decision saved.")}}><label>Requirement<input name="title" defaultValue={r.title} maxLength={200} required/></label><div className="d-form-grid"><label>Category<select name="category" defaultValue={r.category}>{["purchase_order","acceptance","deliverable","amount","billing_recipient","custom"].map(v=><option key={v}>{v}</option>)}</select></label><label>Your decision<select name="status" aria-label="Your decision" defaultValue={r.status}>{["missing","received","conflict","satisfied","waived"].map(v=><option key={v}>{v}</option>)}</select></label></div><EvidenceFields work={work} initial={r.evidence[0]}/>{r.evidence.length>1&&<p className="d-muted">The source fields edit the first reference. Additional references shown above are kept when you save.</p>}<label>Reason for this decision<textarea name="reason" defaultValue={r.reason} minLength={5} maxLength={1000} required/></label><div className="d-actions"><button className="d-primary" disabled={busy}>Save decision</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form>:<button disabled={busy} onClick={()=>setEditing(r.id)}>Review requirement</button>}</article>)}</>}
 {tab==="Resolve"&&<><h2>Close the missing pieces.</h2>{!me.integrations.email&&<p className="d-notice">Save a request draft here, then send it through your own email. Record a verified reply below or add received documents. Dove does not send email.</p>}<form onSubmit={e=>{const f=fields(e);void run(()=>change("request","POST",{requirements:f.getAll("requirements"),body:f.get("body")}),"Request draft saved. No email was sent.")}}><fieldset><legend>Missing requirements</legend>{work.requirements.filter(r=>r.status==="missing").map(r=><label className="d-check" key={r.id}><input type="checkbox" name="requirements" value={r.id}/>{r.title}</label>)}{!work.requirements.some(r=>r.status==="missing")&&<p>No requirements are marked missing.</p>}</fieldset><p>Recipient: <strong>{work.email}</strong></p><label>Request message<textarea name="body" minLength={10} maxLength={3000} rows={5} required/></label><button disabled={busy}>Save request draft</button></form>{work.requests.map(r=><details key={r.id}><summary>{new Date(r.created).toLocaleDateString()} · {r.status}</summary><pre>{r.body}</pre><p className="d-muted">Saved draft only. Copy the text into your email application; Dove does not track delivery.</p><form onSubmit={e=>{const f=fields(e);void run(()=>change("reply","POST",{requestId:r.id,sender:f.get("sender"),text:f.get("text"),verified:true}),"Reply recorded. Review its evidence before changing requirements.")}}><h3>Record a reply you received</h3><label>Verified sender<input type="email" name="sender" defaultValue={r.recipient} required/></label><label>Reply text<textarea name="text" minLength={10} maxLength={20000} required/></label><label className="d-check"><input type="checkbox" required/>I checked the original message and verified the sender and text.</label><button disabled={busy}>Record verified reply</button></form></details>)}</>}
 {tab==="Package"&&<><h2>A good job. All wrapped up.</h2><p>Assemble an immutable package, check the actual PDF and attachments, then approve that version. Download the approved ZIP and deliver it through your own process.</p><p className="d-notice">A reviewed checklist can still omit source requirements. Before assembling or approving any package, check every original document for omissions and compare invoice dates with agreed payment terms.</p>{!complete&&<p className="d-notice">Review and resolve every requirement before assembling a package.</p>}
 {work.packages.map(p=><article key={p.id} className="d-packet"><span className="d-tag">{p.approved?"Approved":p.revision===work.revision?"Needs approval":"Outdated - create a new version"}</span><h3>{p.number}</h3><p className="d-amount">{p.currency} {p.total}</p><p>{p.summary}</p><p>Recipient: {p.recipient}</p><div className="d-actions"><button disabled={busy} onClick={()=>void run(()=>downloadFile(p.pdfId||p.id))}>Download invoice PDF</button><button disabled={busy} onClick={()=>void run(()=>downloadFile(p.id))}>Download package ZIP</button></div><details><summary>Exact version fingerprint</summary><code>{p.digest}</code></details>{!p.approved&&p.revision===work.revision&&<form onSubmit={e=>{e.preventDefault();void run(()=>change("approve","POST",{id:p.id,digest:p.digest,authorize:true}),"This exact package is approved.")}}><label className="d-check"><input type="checkbox" required/>I reviewed the downloaded invoice, recipient, amounts, agreed payment terms and supporting files, checked the original documents for omitted requirements, and approve this exact version.</label><button disabled={busy||!complete}>Approve package</button></form>}{p.approved&&<p className="d-muted">Approved by {p.approvedBy}. Delivery: {p.delivery}</p>}{p.approved&&<p className="d-muted">Download the approved ZIP and deliver it through your existing process. Dove does not send email or track delivery.</p>}</article>)}
 <details open={!work.packages.length}><summary>Assemble {work.packages.length?"a new version":"your first package"}</summary><form onSubmit={e=>{const f=fields(e);void run(()=>change("package","POST",{total:f.get("total"),issue:f.get("issue"),due:f.get("due"),summary:f.get("summary"),evidence:evidence(f),documents:f.getAll("documents"),...(f.get("existingInvoice")?{existingInvoice:f.get("existingInvoice")} :{}),confirmed:true}),"Package assembled. Review the PDF and ZIP before approval.")}}><label>Invoice<select name="existingInvoice"><option value="">Generate a simple invoice from the confirmed total</option>{work.documents.filter(d=>d.mime==="application/pdf").map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><div className="d-form-grid"><label>Confirmed total ({work.currency})<input type="text" inputMode="decimal" name="total" pattern="[0-9]{1,9}(\.[0-9]{1,2})?" placeholder="2400.00" required/></label><label>Invoice date<input type="date" name="issue" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Due date<input type="date" name="due" required/></label></div><EvidenceFields work={work}/><label>Completion summary<textarea name="summary" minLength={5} maxLength={2000} rows={4} required defaultValue={work.description}/></label><fieldset><legend>Supporting documents</legend>{work.documents.map(d=><label className="d-check" key={d.id}><input type="checkbox" name="documents" value={d.id} defaultChecked/>{d.name}</label>)}</fieldset><label className="d-check"><input type="checkbox" required/>I checked the original documents for omitted requirements and verified the total, tax treatment, invoice dates, agreed payment terms and billing recipient. For an existing invoice, I verified its contents match these details.</label><button className="d-primary" disabled={busy||!complete||!work.documents.length}>Assemble package for review</button></form></details></>}
 </section><aside><section className="d-card"><h2>Activity</h2><p className="d-muted">Saved decisions stay with this work.</p><ul className="d-activity">{work.activity.map((a,i)=><li key={i}><time>{new Date(a.at).toLocaleString()}</time><p>{a.text}</p><small>{a.by}</small></li>)}</ul></section><section className="d-card"><h3>Work controls</h3><p className="d-muted">Automation: {work.paused?"paused for this work":me.workspace.paused?"paused in Settings":"enabled"}</p><button disabled={busy} onClick={()=>void run(()=>change("pause","POST",{paused:!work.paused}))}>{work.paused?"Resume this work":"Pause this work"}</button><details><summary>Delete this work</summary><p>This removes documents, packages and saved decisions. Export what you need first.</p><button className="d-danger" disabled={busy} onClick={()=>{if(confirm("Permanently delete this work item and its documents?"))void run(async()=>{await api("work/"+work.id,"DELETE");setWork(null);setList(await api("work"))},"Work deleted.")}}>Delete work item</button></details></section></aside></div>
 </>}
 </main></div>;
}

