"use client";
import { useEffect, useState, useRef } from "react";
import { flushSync } from "react-dom";
import { ArrowUpRight, ArrowRight, Check, Plus } from "lucide-react";
const stages = [
  {label:"Gather", title:"Start with what you have.", text:"Agreements. Completion notes. That last approval. Bring the documents for a finished job into one place.", badge:"01 / DOCUMENTS", rows:["Agreement attached","Completion notes attached","Purchase order missing"]},
  {label:"Resolve", title:"Give every loose end a next step.", text:"See what is missing and where the evidence came from. Review requests before they go out. Keep replies and decisions with the work.", badge:"02 / REQUIREMENTS", rows:["Customer acceptance reviewed","Deliverables confirmed","Purchase order received"]},
  {label:"Approve", title:"Know exactly what you are sending.", text:"Review the invoice, recipients and supporting documents as one package. Approve the exact version, then separately authorize delivery.", badge:"03 / BILLING PACKAGE", rows:["Invoice checked","Supporting evidence reviewed","Ready for your approval"]},
];
export default function Home(){
 const requestId=useRef<string | null>(null); const [stage,setStage]=useState(0); const [busy,setBusy]=useState(false); const [sent,setSent]=useState(false); const [error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); if(busy)return; const form=e.currentTarget; const data=new FormData(form); setBusy(true);setError(""); try{const response=await fetch("/api/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(data),request_id:requestId.current ||= crypto.randomUUID()})}); const result=await response.json();if(!response.ok)throw new Error(result && typeof result === "object" && "error" in result && typeof result.error === "string" ? result.error : "Your request could not be saved. Please try again.");setSent(true);}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);} }
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:"show_dove_workflow_step",title:"Explore a Dove workflow step",description:"Show Gather, Resolve or Approve in the website's illustrative workflow. Does not process documents or submit an access request.",inputSchema:{type:"object",properties:{step:{type:"integer",minimum:1,maximum:3}},required:["step"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const value=input as {step?:number};if(!value||!Number.isInteger(value.step)||value.step!<1||value.step!>3)throw new Error("Choose step 1, 2 or 3.");flushSync(()=>setStage(value.step!-1));document.getElementById("how")?.scrollIntoView({behavior:"instant"});return {step:value.step,label:stages[value.step!-1].label,illustrative:true};}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[]);
 return <><a className="skip" href="#main">Skip to content</a><header className="nav"><a href="#" className="brand" aria-label="Dove home">dove<span>•</span></a><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#inside">Inside Dove</a><a href="/workspace">Open workspace</a></nav><a href="#access" className="nav-cta">Get early access <ArrowUpRight size={18}/></a></header>
 <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dash"/> A BETTER END TO A JOB WELL DONE</p><h1>Work. Done.<br/>Paperwork?<br/><em>Done.</em></h1><p className="intro">You finished the work. Now bring the purchase orders, approvals and final documents across the finish line.</p><a href="#access" className="button lime">Request early access <ArrowUpRight/></a><p className="micro">Invitation access · Built for service businesses</p></div>
 <div className="paper-scene" aria-label="Illustrative example of paperwork becoming a reviewed billing package"><div className="orbit-label">THE LAST MILE, HANDLED.</div><div className="paper back"><span>COMPLETION NOTES</span><i/><i/><i/></div><div className="paper middle"><span>PURCHASE ORDER</span><strong>PO–1042</strong><div className="paper-lines"><i/><i/><i/></div></div><div className="paper front"><div className="paper-top"><span className="paper-logo">dove</span><span>EXAMPLE<br/>WORKFLOW</span></div><p className="document-label">BILLING PACKAGE</p><h2>A good job.<br/>All wrapped up.</h2><div className="paper-checks"><p><Check/> Confirmed amount</p><p><Check/> Acceptance evidence</p><p><Check/> Supporting documents</p></div><div className="paper-bottom"><span>READY FOR REVIEW</span><ArrowUpRight/></div></div><div className="stamp"><Check size={31} strokeWidth={2.5}/><span>LOOSE ENDS<br/>TIED UP.</span></div><span className="scene-caption">Illustration of the workflow. You stay in control.</span></div></section>
 <div className="audience"><span>FOR THE PEOPLE<br/>WHO DO THE WORK.</span><p>Design studios</p><span className="plus">✳</span><p>Consultants</p><span className="plus">✳</span><p>Service teams</p></div>
 <section id="how" className="workflow section"><div className="section-heading"><p className="eyebrow">01 / THE LAST MILE</p><h2>Less chasing.<br/><em>More closure.</em></h2><p>Finished work should not get stuck in an unfinished email thread. Dove gives the paperwork a clear path forward.</p></div><div className="workflow-body"><div className="step-tabs" role="tablist" aria-label="Workflow steps">{stages.map((s,i)=><button key={s.label} role="tab" aria-selected={stage===i} aria-controls="step-panel" id={`step-${i}`} onClick={()=>setStage(i)}><span>0{i+1}</span>{s.label}<ArrowRight size={20}/></button>)}</div><div className="step-panel" id="step-panel" role="tabpanel" aria-labelledby={`step-${stage}`}><span className="eyebrow">{stages[stage].badge}</span><h3>{stages[stage].title}</h3><p>{stages[stage].text}</p><div className="checklist">{stages[stage].rows.map((r,i)=><div key={r}>{stage===0&&i===2?<Plus size={18}/>:<Check size={18}/>}<span>{r}</span></div>)}</div><small>Illustrative workflow · Human review required</small></div></div></section>
 <section id="inside" className="inside section"><div className="inside-heading"><div><p className="eyebrow">02 / EVERYTHING IN CONTEXT</p><h2>The evidence.<br/>The decision.<br/><em>The next move.</em></h2></div><p>Keep the source beside the checklist. See what is ready, what needs a decision, and what happens next. Nothing is sent without the required approvals.</p></div><figure className="product"><div className="windowbar"><span>dove / your workspace</span><span>DOCUMENTS → REVIEW → RESOLVE → PACKAGE</span></div><img src="/product-screenshot.png" alt="Dove's working application with source excerpts beside a reviewed requirement checklist" width="1345" height="890" loading="lazy"/><figcaption>Actual local app with fictional sample data. Live service integrations are still being prepared.</figcaption></figure></section>
 <section className="statement"><p>You did the hard part.</p><h2>Let’s finish<br/><em>the paperwork.</em></h2><span className="asterisk" aria-hidden="true">✳</span></section>
 <section id="access" className="access section"><div><p className="eyebrow">03 / GET IN EARLY</p><h2>Make room<br/>for <em>done.</em></h2><p>Tell us a little about your business and what gets stuck after the work is finished.</p><p className="access-note">Dove is available by invitation. This form registers your interest; it does not create an account or promise an invitation date.</p></div><div className="form-panel">{sent?<div className="success" role="status"><span><Check size={32}/></span><h3>You’re on the list.</h3><p>Your request has been saved. We’ll use the details you provided to follow up about Dove access.</p><a href="#how">Take another look at the workflow <ArrowRight size={18}/></a></div>:<form onSubmit={submit}><div className="form-grid"><label>Your name<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Alex Morgan"/></label><label>Work email<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="alex@yourbusiness.com"/></label></div><label>Business name<input name="business" autoComplete="organization" required maxLength={200} placeholder="Your studio, firm or team"/></label><label>What paperwork keeps you waiting?<textarea name="problem" required minLength={10} maxLength={2000} rows={3} placeholder="Missing purchase orders, approval emails, completion documents…"/></label><div className="trap" aria-hidden="true"><label>Leave this empty<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><input name="consent" type="checkbox" value="yes" required/><span>You may contact me about Dove access. I have read the <a href="#privacy">data notice</a>.</span></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button lime" disabled={busy} type="submit">{busy?"Saving your request…":"Request early access"}<ArrowUpRight/></button><p className="form-footnote">No payment details. No customer documents.</p></form>}</div></section>
 </main><footer><div className="footer-top"><a className="brand" href="#">dove<span>•</span></a><p>From completed work<br/>to completed paperwork.</p><a href="https://github.com/agammann/dove" target="_blank" rel="noreferrer">Explore the source <ArrowUpRight size={17}/></a></div><details id="privacy"><summary>Access request data notice <Plus size={16}/></summary><p>We collect your name, email, business and description to review your interest and contact you about Dove. Requests are stored in the website’s hosted database and are not publicly listed. Do not include confidential customer information. This form does not send your information to an AI model. Requests older than 90 days are removed when new requests are processed. To request removal, submit this form using the same email and write “Delete my access request” in the description. Removal is reviewed manually. Hosting providers may process operational logs to run and protect the site.</p></details><div className="footer-bottom"><span>© {new Date().getFullYear()} Dove</span><span>A little less unfinished.</span><a href="#access">Invitation access</a></div></footer></>;
}
