"use client";
import { useEffect, useState } from "react";
import { flushSync } from "react-dom";
import { ArrowUpRight, ArrowRight, Check, Plus } from "lucide-react";
const stages = [
  {label:"Gather", title:"Start with what you have.", text:"Agreements. Completion notes. That last approval. Bring the documents for a finished job into one place.", badge:"01 / DOCUMENTS", rows:["Agreement attached","Completion notes attached","Purchase order missing"]},
  {label:"Resolve", title:"Give every loose end a next step.", text:"See what is missing and where the evidence came from. Save request drafts for your own email. Keep replies and decisions with the work.", badge:"02 / REQUIREMENTS", rows:["Customer acceptance reviewed","Deliverables confirmed","Purchase order received"]},
  {label:"Approve", title:"Know exactly what you are sending.", text:"Review the invoice, recipients and supporting documents as one package. Approve the exact version, then download it for delivery through your own process.", badge:"03 / BILLING PACKAGE", rows:["Invoice checked","Supporting evidence reviewed","Ready for your approval"]},
];
export default function Home(){
 const [stage,setStage]=useState(0);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:"show_dove_workflow_step",title:"Explore a Dove workflow step",description:"Show Gather, Resolve or Approve in the website's illustrative workflow. Does not process documents.",inputSchema:{type:"object",properties:{step:{type:"integer",minimum:1,maximum:3}},required:["step"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const value=input as {step?:number};if(!value||!Number.isInteger(value.step)||value.step!<1||value.step!>3)throw new Error("Choose step 1, 2 or 3.");flushSync(()=>setStage(value.step!-1));document.getElementById("how")?.scrollIntoView({behavior:"instant"});return {step:value.step,label:stages[value.step!-1].label,illustrative:true};}},{signal:lifecycle.signal});}catch{}return()=>lifecycle.abort();},[]);
 return <><a className="skip" href="#main">Skip to content</a><header className="nav"><a href="#" className="brand" aria-label="Dove home">dove<span>•</span></a><nav aria-label="Main navigation"><a href="#how">How it works</a><a href="#inside">Inside Dove</a><a href="/workspace">Open workspace</a></nav><a href="/workspace" className="nav-cta">Open Dove <ArrowUpRight size={18}/></a></header>
 <main id="main"><section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="dash"/> A BETTER END TO A JOB WELL DONE</p><h1>Work. Done.<br/>Paperwork?<br/><em>Done.</em></h1><p className="intro">You finished the work. Now bring the purchase orders, approvals and final documents across the finish line.</p><a href="/workspace" className="button lime">Open your workspace <ArrowUpRight/></a><p className="micro">No login · Local workspace · Optional API key</p></div>
 <div className="paper-scene" aria-label="Illustrative example of paperwork becoming a reviewed billing package"><div className="orbit-label">THE LAST MILE, HANDLED.</div><div className="paper back"><span>COMPLETION NOTES</span><i/><i/><i/></div><div className="paper middle"><span>PURCHASE ORDER</span><strong>PO–1042</strong><div className="paper-lines"><i/><i/><i/></div></div><div className="paper front"><div className="paper-top"><span className="paper-logo">dove</span><span>EXAMPLE<br/>WORKFLOW</span></div><p className="document-label">BILLING PACKAGE</p><h2>A good job.<br/>All wrapped up.</h2><div className="paper-checks"><p><Check/> Confirmed amount</p><p><Check/> Acceptance evidence</p><p><Check/> Supporting documents</p></div><div className="paper-bottom"><span>READY FOR REVIEW</span><ArrowUpRight/></div></div><div className="stamp"><Check size={31} strokeWidth={2.5}/><span>LOOSE ENDS<br/>TIED UP.</span></div><span className="scene-caption">Illustration of the workflow. You stay in control.</span></div></section>
 <div className="audience"><span>FOR THE PEOPLE<br/>WHO DO THE WORK.</span><p>Design studios</p><span className="plus">✳</span><p>Consultants</p><span className="plus">✳</span><p>Service teams</p></div>
 <section id="how" className="workflow section"><div className="section-heading"><p className="eyebrow">01 / THE LAST MILE</p><h2>Less chasing.<br/><em>More closure.</em></h2><p>Finished work should not get stuck in an unfinished email thread. Dove gives the paperwork a clear path forward.</p></div><div className="workflow-body"><div className="step-tabs" role="tablist" aria-label="Workflow steps">{stages.map((s,i)=><button key={s.label} role="tab" aria-selected={stage===i} aria-controls="step-panel" id={`step-${i}`} onClick={()=>setStage(i)}><span>0{i+1}</span>{s.label}<ArrowRight size={20}/></button>)}</div><div className="step-panel" id="step-panel" role="tabpanel" aria-labelledby={`step-${stage}`}><span className="eyebrow">{stages[stage].badge}</span><h3>{stages[stage].title}</h3><p>{stages[stage].text}</p><div className="checklist">{stages[stage].rows.map((r,i)=><div key={r}>{stage===0&&i===2?<Plus size={18}/>:<Check size={18}/>}<span>{r}</span></div>)}</div><small>Illustrative workflow · Human review required</small></div></div></section>
 <section id="inside" className="inside section"><div className="inside-heading"><div><p className="eyebrow">02 / EVERYTHING IN CONTEXT</p><h2>The evidence.<br/>The decision.<br/><em>The next move.</em></h2></div><p>Keep the source beside the checklist. See what is ready, what needs a decision, and what happens next. Documents are saved in your browser. Hosted analysis is optional. Download approved packages for your own delivery process.</p></div><figure className="product"><div className="windowbar"><span>dove / your workspace</span><span>DOCUMENTS → REVIEW → RESOLVE → PACKAGE</span></div><img src="/product-screenshot.png" alt="Dove browser workspace with fictional source excerpts beside a proposed requirement" width="1440" height="1000" loading="lazy"/><figcaption>Dove workflow with fictional sample data. The current workspace runs locally in your browser.</figcaption></figure></section>
 <section className="statement"><p>You did the hard part.</p><h2>Let’s finish<br/><em>the paperwork.</em></h2><span className="asterisk" aria-hidden="true">✳</span></section>
 <section id="access" className="access section"><div><p className="eyebrow">03 / OPEN AND START</p><h2>Make room<br/>for <em>done.</em></h2><p>Open Dove and bring your documents. No account or invitation is needed. Use device analysis, manual review, or optional hosted analysis with your own API key.</p><a href="/workspace" className="button lime">Open your workspace <ArrowUpRight/></a></div><div className="form-panel"><h3>Your browser. Your workspace.</h3><p>Documents and saved decisions stay on this device, in this browser profile. Device analysis runs on compatible WebGPU hardware after a model download. Optional hosted analysis uses your OpenAI API account and sends extracted document text to OpenAI.</p><p>Use Settings to export a complete backup, including original files and billing packages. Restore that backup to move work to another browser. There is no automatic sync or shared access.</p><p>Clearing site data can erase your work. Anyone using this browser profile can open it, so use your own device and keep backups somewhere private.</p></div></section>
 </main><footer><div className="footer-top"><a className="brand" href="#">dove<span>•</span></a><p>From completed work<br/>to completed paperwork.</p><a href="https://github.com/agammann/dove" target="_blank" rel="noreferrer">Explore the source <ArrowUpRight size={17}/></a></div><details id="privacy"><summary>Data and storage notice <Plus size={16}/></summary><p>Dove stores documents, extracted text, billing details and decisions in your browser’s IndexedDB storage. It does not upload those records to a workspace database. Device analysis stays local. If you choose hosted analysis, complete extracted document text and filenames, plus the work title, customer and description, pass through this server to OpenAI using your key. Your key is kept only in tab memory and is not included in backups. API usage is billed to your account; requests disable provider response storage, and OpenAI data policies apply. Model files download from public hosts; the website and asset hosts may process normal request metadata. Local records and backup ZIPs are not encrypted by Dove. Browser cleanup, private browsing and changing profiles can remove access to saved work. Export backups regularly. There are no accounts, invitations, automatic email delivery or cross-device sync. Earlier hosted records have not been made public or automatically copied into this browser.</p></details><div className="footer-bottom"><span>© {new Date().getFullYear()} Dove</span><span>A little less unfinished.</span><a href="/workspace">Open Dove</a></div></footer></>;
}
