import { env } from "cloudflare:workers";
import { z } from "zod";
import { database } from "../../../../db/raw";
import { uid, now, digest, member, identity, row, save, event, invalidate, validEvidence, requirementInput, analyze, limitedBody, body, sameOrigin, response, failure, need, bucket, invite, throttle, Problem } from "../../../../lib/dove";
import { extract, cents, money, invoice, archive } from "../../../../lib/dove-files";
import type { Work, DocumentRecord, Packet } from "../../../../lib/dove-types";
export const dynamic="force-dynamic";
const createInput=z.object({title:z.string().trim().min(1).max(200),customer:z.string().trim().min(1).max(200),contactName:z.string().trim().min(1).max(200),email:z.string().email().max(254),authorized:z.boolean(),currency:z.enum(["USD","EUR","GBP","CAD","AUD"]),description:z.string().trim().min(1).max(2000)}).strict();
const packageInput=z.object({total:z.string(),issue:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),summary:z.string().trim().min(5).max(2000),evidence:requirementInput.shape.evidence.min(1),documents:z.array(z.string().uuid()).max(10),existingInvoice:z.string().uuid().optional(),confirmed:z.literal(true)}).strict();
function path(r:Request){return new URL(r.url).pathname.replace(/^\/api\/dove\/?/,"").split("/").filter(Boolean)}
async function filesFor(org:string,work:string){return (await database().prepare("SELECT id,storage_key,size,name,mime FROM dove_files WHERE org_id=? AND work_id=?").bind(org,work).all<{id:string;storage_key:string;size:number;name:string;mime:string}>()).results}
async function storeFile(org:string,wid:string,id:string,name:string,mime:string,bytes:Uint8Array){const quota=await database().prepare("UPDATE dove_workspaces SET bytes=bytes+?,file_count=file_count+1 WHERE id=? AND bytes+?<=67108864 AND file_count<100 RETURNING id").bind(bytes.length,org,bytes.length).first();need(quota,"Workspace storage limit reached. Remove unneeded work before uploading.",409);const key=org+"/"+wid+"/"+id;try{await bucket().put(key,bytes,{httpMetadata:{contentType:mime}});await database().prepare("INSERT INTO dove_files (id,org_id,work_id,storage_key,name,mime,size) VALUES (?,?,?,?,?,?,?)").bind(id,org,wid,key,name,mime,bytes.length).run()}catch(e){await database().prepare("UPDATE dove_workspaces SET bytes=MAX(0,bytes-?),file_count=MAX(0,file_count-1) WHERE id=?").bind(bytes.length,org).run();await bucket().delete(key).catch(()=>{});throw e}}
async function removeFile(org:string,id:string){const f=await database().prepare("SELECT storage_key,size FROM dove_files WHERE org_id=? AND id=?").bind(org,id).first<{storage_key:string;size:number}>();if(!f)return;await bucket().delete(f.storage_key);await database().batch([database().prepare("DELETE FROM dove_files WHERE org_id=? AND id=?").bind(org,id),database().prepare("UPDATE dove_workspaces SET bytes=MAX(0,bytes-?),file_count=MAX(0,file_count-1) WHERE id=?").bind(f.size,org)])}
async function cleanup(org:string){const deleted=(await database().prepare("SELECT id FROM dove_work WHERE org_id=? AND deleted=1 LIMIT 5").bind(org).all<{id:string}>()).results;for(const w of deleted){for(const f of await filesFor(org,w.id))await removeFile(org,f.id);await database().prepare("DELETE FROM dove_work WHERE org_id=? AND id=? AND deleted=1").bind(org,w.id).run()}}
async function active(org:string,id:string){const a=await database().prepare("SELECT id FROM dove_work WHERE org_id=? AND id=? AND deleted=0").bind(org,id).first();need(a,"Work item not found.",404);return row(org,id)}
async function liveSend(input:Record<string,unknown>,id:string){need(env.RESEND_API_KEY&&env.EMAIL_FROM,"Email delivery is not configured. You can still download the approved package.",503);try{const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"Authorization":"Bearer "+env.RESEND_API_KEY,"Content-Type":"application/json","Idempotency-Key":id},body:JSON.stringify({from:env.EMAIL_FROM,...input}),signal:AbortSignal.timeout(25000)});if(r.status>=500)return {status:"uncertain"};if(!r.ok)return {status:"failed"};const d=await r.json() as {id?:string};return d.id?{status:"provider_accepted",providerId:d.id}:{status:"uncertain"}}catch{return {status:"uncertain"}}}
async function handler(request:Request){
const p=path(request),method=request.method;
if(p[0]==="health")return response({status:"ok"});
if(p[0]==="admin"&&method==="POST"){
 need(env.DOVE_ADMIN_TOKEN&&request.headers.get("Authorization")==="Bearer "+env.DOVE_ADMIN_TOKEN,"Not authorized.",401);
 const data=z.object({name:z.string().trim().min(1).max(200),email:z.string().email().nullable()}).strict().parse(await body(request));
 const id=uid();await database().prepare("INSERT INTO dove_workspaces (id,name,billing,paused,bytes,file_count) VALUES (?,?,'',1,0,0)").bind(id,data.name).run();return response({org:id,token:await invite(id,data.email)},201);
}
const user=await identity();
if(method!=="GET")sameOrigin(request);
if(p[0]==="accept"&&method==="POST"){
 const {token}=z.object({token:z.string().min(60).max(100)}).strict().parse(await body(request));const hash=await digest(token);
 const existing=await database().prepare("SELECT org_id FROM dove_members WHERE user_id=?").bind(user.userId).first();need(!existing,"This account already has a workspace.",409);
 const i=await database().prepare("SELECT org_id,email FROM dove_invitations WHERE hash=? AND used_by IS NULL AND expires>?").bind(hash,Date.now()).first<{org_id:string;email:string|null}>();need(i&&(!i.email||i.email===user.email.toLowerCase()),"This invitation is invalid, expired, used, or addressed to another email.",403);
 await database().batch([database().prepare("UPDATE dove_invitations SET used_by=? WHERE hash=? AND used_by IS NULL AND expires>?").bind(user.userId,hash,Date.now()),database().prepare("INSERT INTO dove_members (user_id,org_id,email) SELECT ?,org_id,? FROM dove_invitations WHERE hash=? AND used_by=?").bind(user.userId,user.email,hash,user.userId)]);
 const m=await database().prepare("SELECT org_id FROM dove_members WHERE user_id=?").bind(user.userId).first();need(m,"This invitation has already been used.",409);return response({ok:true});
}
if(p[0]==="session"&&method==="GET")return response({user:{id:user.userId,name:user.displayName,email:user.email}});
const {org}=await member();
if(p[0]==="me"&&method==="GET"){await cleanup(org.id).catch(()=>{});return response({workspace:org,user:{name:user.displayName,email:user.email},integrations:{ai:!!env.OPENAI_API_KEY,email:!!env.RESEND_API_KEY&&!!env.EMAIL_FROM,inbound:false},limits:{fileMB:4,pages:40,documents:10,workspaceMB:64},signout:"/signout-with-chatgpt?return_to=/"})}
if(method!=="GET")await throttle(org.id);
if(p[0]==="settings"&&method==="PUT"){
 const d=z.object({name:z.string().trim().min(1).max(200),billing:z.string().trim().min(1).max(1500),paused:z.boolean()}).strict().parse(await body(request));await database().prepare("UPDATE dove_workspaces SET name=?,billing=?,paused=? WHERE id=?").bind(d.name,d.billing,d.paused?1:0,org.id).run();return response({ok:true});
}
if(p[0]==="invite"&&method==="POST"){const d=z.object({email:z.string().email()}).strict().parse(await body(request));return response({token:await invite(org.id,d.email),expiresHours:72})}
if(p[0]==="export"&&method==="GET"){const works=(await database().prepare("SELECT data FROM dove_work WHERE org_id=? AND deleted=0").bind(org.id).all<{data:string}>()).results.map(x=>JSON.parse(x.data));return new Response(JSON.stringify({workspace:org,work:works},null,2),{headers:{"Content-Type":"application/json","Content-Disposition":"attachment; filename=dove-workspace.json","Cache-Control":"no-store"}})}
if(p[0]==="file"&&method==="GET"){
 const f=await database().prepare("SELECT f.* FROM dove_files f JOIN dove_work w ON w.id=f.work_id AND w.org_id=f.org_id WHERE f.id=? AND f.org_id=? AND w.deleted=0").bind(p[1],org.id).first<{storage_key:string;name:string;mime:string}>();need(f,"File not found.",404);const object=await bucket().get(f.storage_key);need(object,"File is unavailable. Please retry.",503);return new Response(object.body,{headers:{"Content-Type":f.mime,"Content-Disposition":(new URL(request.url).searchParams.has("preview")&&f.mime==="application/pdf"?"inline":"attachment")+"; filename*=UTF-8''"+encodeURIComponent(f.name),"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff","Content-Security-Policy":"sandbox"}})
}
if(p[0]!=="work")throw new Problem("Not found.",404);
if(p.length===1&&method==="GET"){const list=(await database().prepare("SELECT data FROM dove_work WHERE org_id=? AND deleted=0 ORDER BY updated DESC LIMIT 100").bind(org.id).all<{data:string}>()).results.map(x=>{const w=JSON.parse(x.data) as Work;return {id:w.id,title:w.title,customer:w.customer,status:w.status,created:w.created}});return response(list)}
if(p.length===1&&method==="POST"){
 const d=createInput.parse(await body(request));const count=await database().prepare("SELECT COUNT(*) AS n FROM dove_work WHERE org_id=?").bind(org.id).first<{n:number}>();need((count?.n||0)<100,"Workspace work-item limit reached.",409);
 const w:Work={...d,id:uid(),status:"Add documents",revision:0,documents:[],requirements:[],packages:[],requests:[],activity:[],created:now(),calls:0,paused:false};event(w,user.email,"Work item created.");const inserted=await database().prepare("INSERT INTO dove_work (id,org_id,data,version,updated,deleted) SELECT ?,?,?,0,?,0 WHERE (SELECT COUNT(*) FROM dove_work WHERE org_id=?)<100 RETURNING id").bind(w.id,org.id,JSON.stringify(w),Date.now(),org.id).first();need(inserted,"Workspace work-item limit reached.",409);return response(w,201)
}
const {work:w,version:v}=await active(org.id,p[1]);
if(p.length===2&&method==="GET")return response(w);
if(p.length===2&&method==="DELETE"){await database().prepare("UPDATE dove_work SET deleted=1 WHERE org_id=? AND id=?").bind(org.id,w.id).run();await cleanup(org.id).catch(()=>{});return response({ok:true,message:"Work is inaccessible. Stored-file cleanup will retry on your next workspace visit if storage is unavailable."})}
if(p[2]==="pause"&&method==="POST"){const d=z.object({paused:z.boolean()}).strict().parse(await body(request));w.paused=d.paused;event(w,user.email,d.paused?"Automation paused.":"Automation resumed.");await save(org.id,w,v);return response(w)}
if(p[2]==="document"&&method==="POST"){
 need(w.documents.length<10,"A work item may contain at most 10 documents.",409);const raw=await limitedBody(request,4*1024*1024+20000);const form=await new Response(raw,{headers:{"Content-Type":request.headers.get("content-type")||""}}).formData();const f=form.get("file");need(f instanceof File,"Choose a file.");const name=f.name.replace(/[\\/\x00-\x1f]/g,"_").slice(0,150);const bytes=new Uint8Array(await f.arrayBuffer());const pages=await extract(bytes,name);need(w.documents.flatMap(x=>x.pages).join("").length+pages.join("").length<=200000,"This work item contains too much text.",413);
 const id=uid(),mime=/\.pdf$/i.test(name)?"application/pdf":"text/plain";await storeFile(org.id,w.id,id,name,mime,bytes);const d:DocumentRecord={id,name,mime,size:bytes.length,pages,approved:false};w.documents.push(d);invalidate(w);event(w,user.email,"Document uploaded: "+name+". Checklist and package approvals require review.");for(const r of w.requirements)r.status="received";try{await save(org.id,w,v)}catch(e){await removeFile(org.id,id).catch(()=>{});throw e}return response(w)
}
if(p[2]==="analyze"&&method==="POST"){
 need(!w.paused&&!org.paused,"Resume automation in Settings and on this work item first.",409);need(w.calls<20,"This work item has reached its AI call allowance.",409);need(w.documents.length,"Upload a document first.");await throttle(org.id,"ai");w.calls++;w.status="Analyzing";event(w,user.email,"AI analysis requested. Existing decisions will be replaced only after a valid result.");await save(org.id,w,v);
 try{const proposed=await analyze(w);w.requirements=proposed;invalidate(w);event(w,"Dove","AI proposed "+proposed.length+" source-linked requirements. Human review is required.");await save(org.id,w,v+1);return response(w)}catch(e){const latest=await active(org.id,w.id);if(latest.version===v+1){latest.work.status="Review required";event(latest.work,"Dove","Analysis did not finish. Saved documents and prior checklist retained.");await save(org.id,latest.work,latest.version)}throw e}
}
if(p[2]==="requirement"&&method==="PUT"){
 const data=z.object({id:z.string().uuid().optional(),requirement:requirementInput}).strict().parse(await body(request));const r=data.requirement;need(r.status==="waived"||r.evidence.length>0,"Attach source evidence or explicitly waive this requirement.");need(r.evidence.every(e=>validEvidence(w,e)),"Source quote must match the chosen document and page.");need(w.requirements.length<30||data.id,"Requirement limit reached.");const pos=w.requirements.findIndex(x=>x.id===data.id);need(!data.id||pos>=0,"Requirement not found.",404);const item={...r,id:data.id||uid(),reviewedBy:user.email};if(pos>=0)w.requirements[pos]=item;else w.requirements.push(item);invalidate(w);w.status=w.requirements.every(x=>["satisfied","waived"].includes(x.status))?"Ready to package":"Review required";event(w,user.email,r.title+": "+r.status+". "+r.reason);await save(org.id,w,v);return response(w)
}
if(p[2]==="reply"&&method==="POST"){
 const d=z.object({requestId:z.string().uuid(),text:z.string().trim().min(10).max(20000),sender:z.string().email(),verified:z.literal(true)}).strict().parse(await body(request));const req=w.requests.find(x=>x.id===d.requestId);need(req,"Request not found.",404);need(d.sender.toLowerCase()===req.recipient.toLowerCase(),"The sender must match the authorized contact.");need(w.documents.length<10,"Document limit reached.");const bytes=new TextEncoder().encode(d.text),id=uid();await storeFile(org.id,w.id,id,"Recorded reply.txt","text/plain",bytes);w.documents.push({id,name:"Recorded reply from "+d.sender,mime:"text/plain",size:bytes.length,pages:[d.text],approved:false});req.status="reply_recorded";invalidate(w);event(w,user.email,"Operator recorded a reply and verified its source. Review its evidence; it is not an automatically verified email.");try{await save(org.id,w,v)}catch(e){await removeFile(org.id,id).catch(()=>{});throw e}return response(w)
}
if(p[2]==="request"&&method==="POST"){
 need(!org.paused&&!w.paused,"Automation is paused.",409);need(w.authorized,"The customer contact has not been authorized.",409);need(env.RESEND_API_KEY&&env.EMAIL_FROM&&env.REPLY_DOMAIN,"Email requests are not configured yet.",503);need(w.requests.length<10,"Request allowance reached.",409);const d=z.object({requirements:z.array(z.string().uuid()).min(1).max(20),body:z.string().trim().min(10).max(3000),authorize:z.literal(true)}).strict().parse(await body(request));need(d.requirements.every(id=>w.requirements.some(r=>r.id===id&&r.status==="missing")),"Select missing requirements.");const req={id:uid(),requirements:d.requirements,body:d.body,recipient:w.email,status:"sending",created:now()};w.requests.push(req);event(w,user.email,"Request explicitly authorized for "+w.email);await save(org.id,w,v);
 const sent=await liveSend({to:[w.email],subject:"Documentation for "+w.title,text:d.body,reply_to:"reply+"+req.id+"@"+env.REPLY_DOMAIN},req.id);const latest=await active(org.id,w.id);const record=latest.work.requests.find(x=>x.id===req.id)!;Object.assign(record,sent);event(latest.work,"Dove","Request: "+sent.status+". Provider acceptance does not establish delivery.");await save(org.id,latest.work,latest.version);return response(latest.work)
}
if(p[2]==="package"&&method==="POST"){
 need(w.requirements.length>0&&w.requirements.every(r=>["satisfied","waived"].includes(r.status)),"Resolve and review every requirement before packaging.",409);need(w.authorized,"Authorize the billing contact first.",409);need(w.packages.length<10,"Package version limit reached.",409);need(org.billing,"Save your business billing details in Settings first.",409);
 const d=packageInput.parse(await body(request));const total=cents(d.total);need(total>0,"The invoice total must be positive.");need(d.due>=d.issue&&Number.isFinite(Date.parse(d.issue))&&Number.isFinite(Date.parse(d.due))&&new Date(d.issue).toISOString().slice(0,10)===d.issue&&new Date(d.due).toISOString().slice(0,10)===d.due,"Enter valid issue and due dates.");need(d.evidence.every(e=>validEvidence(w,e)),"The amount evidence must match its source.");const quoted=d.evidence.map(e=>e.quote).join(" ");const values=[...quoted.matchAll(/\d[\d,]*(?:\.\d{1,2})?/g)].map(x=>x[0].replace(/,/g,""));need(values.some(x=>{try{return cents(x)===total}catch{return false}}),"The total must appear in the selected source evidence.");need(new Set(d.documents).size===d.documents.length&&d.documents.every(id=>w.documents.some(x=>x.id===id)),"Choose existing, distinct supporting documents.");const existing=d.existingInvoice?w.documents.find(x=>x.id===d.existingInvoice&&x.mime==="application/pdf"):undefined;need(!d.existingInvoice||existing,"Choose a PDF for the existing invoice.");
 const id=uid(),number="DV-"+w.id.slice(0,8).toUpperCase()+"-"+(w.packages.length+1);const manifest={number,work:w.title,customer:w.customer,currency:w.currency,total:money(total),recipient:w.email,business:org.name,billing:org.billing,issue:d.issue,due:d.due,summary:d.summary,evidence:d.evidence,documents:d.documents,revision:w.revision};const all:Record<string,Uint8Array>={};
 if(existing){const f=await bucket().get(org.id+"/"+w.id+"/"+existing.id);need(f,"Invoice file unavailable.",503);all["invoice.pdf"]=new Uint8Array(await f.arrayBuffer())}
 else all["invoice.pdf"]=await invoice([org.name,org.billing,"INVOICE "+number,"Customer: "+w.customer,"To: "+w.email,"Issue: "+d.issue+"    Due: "+d.due,"Completed work: "+w.title,d.summary,"Confirmed total: "+w.currency+" "+money(total),"Source-supported total; tax treatment confirmed by the operator."]);
 let size=all["invoice.pdf"].length;
 for(const docId of d.documents){if(docId===d.existingInvoice)continue;const doc=w.documents.find(x=>x.id===docId)!;const object=await bucket().get(org.id+"/"+w.id+"/"+docId);need(object,"Supporting document unavailable.",503);size+=doc.size;need(size<12*1024*1024,"Keep the package under 12 MB.",413);all["supporting/"+docId.slice(0,8)+"-"+doc.name]=new Uint8Array(await object.arrayBuffer())}
 const bytes=archive(all,manifest,d.summary);const hash=await digest(bytes);await storeFile(org.id,w.id,id,number+".zip","application/zip",bytes);const pdfId=uid();try{await storeFile(org.id,w.id,pdfId,number+".pdf","application/pdf",all["invoice.pdf"])}catch(e){await removeFile(org.id,id).catch(()=>{});throw e}
 const packet:Packet={id,number,digest:hash,total:money(total),currency:w.currency,recipient:w.email,revision:w.revision,approved:false,created:now(),documents:d.documents,summary:d.summary,delivery:"not_sent"};w.packages.unshift({...packet,pdfId} as Packet);event(w,user.email,"Package "+number+" assembled. Review the exact PDF and attachments before approval.");try{await save(org.id,w,v)}catch(e){await removeFile(org.id,id).catch(()=>{});await removeFile(org.id,pdfId).catch(()=>{});throw e}return response(w)
}
if(p[2]==="approve"&&method==="POST"){const d=z.object({id:z.string().uuid(),digest:z.string(),authorize:z.literal(true)}).strict().parse(await body(request));const packet=w.packages.find(x=>x.id===d.id);need(packet&&packet.digest===d.digest&&packet.revision===w.revision,"The package changed; assemble and review the current version.",409);need(w.requirements.every(r=>["satisfied","waived"].includes(r.status)),"Review all requirements.",409);packet.approved=true;packet.approvedBy=user.email;w.status="Approved";event(w,user.email,"Exact package "+packet.number+" approved, including amount, recipient and listed attachments.");await save(org.id,w,v);return response(w)}
if(p[2]==="deliver"&&method==="POST"){
 need(env.RESEND_API_KEY&&env.EMAIL_FROM,"Email delivery is not configured. Download the approved ZIP instead.",503);need(!org.paused&&!w.paused&&w.authorized,"Automation is paused or the contact is not authorized.",409);const d=z.object({id:z.string().uuid(),digest:z.string(),authorize:z.literal(true)}).strict().parse(await body(request));const packet=w.packages.find(x=>x.id===d.id);need(packet&&packet.approved&&packet.digest===d.digest&&packet.revision===w.revision,"Approve the current exact package before delivery.",409);need(packet.delivery==="not_sent","This package already has a delivery attempt. Reconcile uncertain sends before retrying.",409);packet.delivery="sending";event(w,user.email,"Delivery of "+packet.number+" explicitly authorized to "+packet.recipient);await save(org.id,w,v);const object=await bucket().get(org.id+"/"+w.id+"/"+packet.id);need(object,"Package unavailable. No email was submitted; contact the operator to reconcile this attempt.",503);const bytes=new Uint8Array(await object.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const sent=await liveSend({to:[packet.recipient],subject:"Billing package for "+w.title,text:packet.summary,attachments:[{filename:packet.number+".zip",content:btoa(binary)}]},packet.id);
 const latest=await active(org.id,w.id);const pp=latest.work.packages.find(x=>x.id===packet.id)!;pp.delivery=sent.status;pp.providerId=sent.providerId;latest.work.status=sent.status==="provider_accepted"?"Sent to provider":"Delivery needs attention";event(latest.work,"Dove","Package: "+sent.status+". This does not establish customer acceptance or payment.");await save(org.id,latest.work,latest.version);return response(latest.work)
}
throw new Problem("Not found.",404);
}
export async function GET(r:Request){try{return await handler(r)}catch(e){return failure(e)}finally{if(r.body&&!r.bodyUsed){if(Number(r.headers.get("content-length")||0)<=24000){try{await limitedBody(r,24000)}catch{}}else await r.body.cancel().catch(()=>{})}}}
export const POST=GET;export const PUT=GET;export const DELETE=GET;
